[project]
name = "peter_cullen_burbery_python_functions"
version = "0.1.0"
description = "Utility functions by Peter Cullen Burbery, including date_time_stamp"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
  { name = "Peter Cullen Burbery", email = "peter.cullen.burbery@gmail.com" }
]
dependencies = ["tzlocal"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
