[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"npsam.button_images" = ["*.png"]

[project]
name = "npsam"
version = "3.2.2"
dependencies = [
    "numba==0.60.0",
    "opencv-python==4.10.0.84",
    "pandas==2.2.2",
    "matplotlib==3.8.2",
    "scikit-image==0.24.0",
    "ipympl==0.9.4",
    "PyQt6==6.7.0",
    "ultralytics==8.3.27",
    "jupyterlab==4.2.2",
    "clip==0.2.0",
    "hyperspy[all]==2.1.1",
	"exspy==0.2",
	"rosettasciio==0.6",
    "parse==1.20.2",
	"sparse==0.15.4",
    "tifffile==2024.6.18",
    "matplotlib_scalebar==0.9.0"
]

requires-python = ">= 3.10"
authors = [
    {name = "Rohde, R. & Villadsen, T.", email = "rasmus@inano.au.dk"}
]
description="NP-SAM is an easy-to-use segmentation and analysis tool for nanoparticles and more."
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE.txt"]
keywords = ["nanoparticles", "segmentation"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Intended Audience :: Science/Research",
]
