[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "excel-list-transform"
version = "0.8.0"
authors = [
  { name="Tom Bj√∂rkholm", email="klausuler_linnet0q@icloud.com" },
]
description = "Transform a list in excel or CSV"
readme = "README_pypi.md"
requires-python = "<3.11,>=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[project.urls]
"Source code" = "https://bitbucket.org/tom-bjorkholm/excel-list-transform"
