[workspace]
members = ["scraprr", "scrapr-bindings", "scrapr-core"]
resolver = "3"


[workspace.dependencies]
native-tls = "0.2.14"
anyhow = { version = "*" }
pyo3 = { version = "0.25.1", features = ["extension-module"] }

