[project]
name = "django-admin-commander"
version = "0.3.0"
description = "A Django app to run management commands from the admin panel"
readme = "README.md"
authors = [
    { name = "Lucas Camillo" }
]
requires-python = ">=3.11"
dependencies = [
    "django>=4.2",
]

[project.urls]
Home = "https://github.com/Lcrs123/django-admin-commander"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
