[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "SpaMV"
version = "1.0.14"
dependencies=["pyro-ppl", "scanpy", "torch_geometric", "squidpy==1.6.2", "dask[dataframe]==2024.11.2"]
requires-python = ">=3.12"
authors = [
  { name="Yang Liu", email="yangliu1214@hkbu.edu.hk" },
]
description = "The Python package for a spatial multi-omics integration algorithm called SpaMV."
readme = "README.md"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/enderlogic/SpaMV"
Issues = "https://github.com/enderlogic/SpaMV/issues"