[project]
name = "cisco-nso-mcp-server"
version = "2.4.0"
license = "MIT"
description = "Cisco NSO MCP Server"
readme = "README.md"
authors = [
    {name = "Darren Bono", email = "dbono215@gmail.com"},
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "cisco-nso-restconf>=1.0.5",
    "fastmcp>=2.3.4",
    "httpx>=0.28.1",
    "python-dotenv>=1.1.0",
]

[project.urls]
"Homepage" = "https://github.com/dbono711/cisco-nso-mcp-server"

[project.scripts]
cisco-nso-mcp-server = "cisco_nso_mcp_server.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
