[package]
name = "xlsx"
version = "0.0.5"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "xlsx"
crate-type = ["cdylib"]

[dependencies]
cargo-llvm-cov = "0.6.14"
pyo3 = { version = "0.25.0", features = ["extension-module", "abi3-py39"] }
quick-xml = { version = "0.38", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
zip = "0.6"
chrono = "0.4"
thiserror = "2.0.12"
