[project]
name = "yta-video-editor"
version = "0.0.3"
description = "Youtube Autonomous Video Editor Module"
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    "yta_validation (>=0.0.1,<1.0.0)",
    "yta_colors (>=0.0.1,<1.0.0)",
    "yta_audio_base (>=0.0.1,<1.0.0)",
    # TODO: I think I should separate AI and advanced
    # functionality from the basic one, so when I want
    # to simply change the volume or the brightness, I
    # don't need to import AI libraries that generate
    # images or things like that.
    "yta_image (>=0.0.1,<1.0.0)",
    "yta_general_utils (>=0.0.1,<1.0.0)",
    "yta_video_base (>=0.0.1,<1.0.0)",
    # TODO: Where is moviepy (?)

    "yta_video_moviepy (>=0.0.1,<1.0.0)",
    "yta_constants (>=0.0.1,<1.0.0)",
]

[tool.poetry]
packages = [{include = "yta_video_editor", from = "src"}]

# # Optional dependencies below
# [tool.poetry.group.optional]
# optional = true

# [tool.poetry.group.optional.dependencies]
# # Optional dependencies above

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
