[project]
name = "uasgi"
version = "0.4.0"
description = "uASGI: A High-Performance ASGI Web Server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.1",
    "httptools>=0.6.4",
    "uvloop>=0.21.0",
    "watchdog>=6.0.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
     "Programming Language :: Python :: 3.10",
     "License :: OSI Approved :: MIT License",
     "Operating System :: OS Independent",
     "Topic :: Internet :: WWW/HTTP :: WSGI :: Server",
     "Framework :: AsyncIO",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.12.4",
    "ty>=0.0.1a14",
]
