[project]
name = "omuplugin_chat"
version = "0.9.12"
description = "チャットを管理するためのOMUAPPSプラグイン"
authors = [
    { name = "am230", email = "111672334+am230@users.noreply.github.com" },
]
dependencies = ["loguru>=0.7.2", "omu_chat>=0.9.12", "iwashi>=3.1.1"]
readme = "README.md"
requires-python = ">= 3.12"

[project.entry-points."omu.plugins"]
plugin = "omuplugin_chat:plugin"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true
