[project]
name = "sampling_tille"
version = "0.2.0"
description = "Sampling routines ported from the sampling R package."
authors = [
    {name = "Stippe"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy (>=1.16,<3.0.0)",
    "cvxpy (>=1.6.3,<2.0.0)",
    "pyscipopt (>=5.4.1,<6.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "geopandas (>=1.0.1,<2.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "rioxarray (==0.18.2)",
    "jax (==0.5.0)",
    "scipy (==1.15.2)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
snakeviz = "^2.2.2"
coverage = "^7.6.12"
