[tool.setuptools.packages.find]
include = ["luck_room_v1"]
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "luck-room-v1"
version = "0.1.4"
description = "A simple luck based game."
authors = [
    { name="Braeden Sy Tan", email="braedenjairsytan@icloud.com" }
]
readme = "README.md"
license = "GPL-3.0-only"
requires-python = ">=3.7"
dependencies = []

[project.scripts]
luckroom = "luck_room_v1.LuckRoom:main"

[project.urls]
"Homepage" = "https://github.com/DuckyBoi-XD/Python-Learn-Gamble"
