[project]
name = "paral"
version = "0.2.0"
description = "An Git User/Credential Switcher"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.2",
    "questionary>=2.1.0",
    "typer>=0.16.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Topic :: Utilities",
    "Topic :: Software Development :: Version Control :: Git"
]
license = "MIT"

[project.urls]
Repository = "https://github.com/aoi-cistus/parallel"
Issues = "https://github.com/aoi-cistus/parallel/issues"

[project.scripts]
paral = "parallel.cli:app"
prl = "parallel.legacy:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/parallel"]
