[project]
name = "dwgdbserver"
version = "2.3.1"
description = "A gdbserver for debugWIRE"
authors = [
    {name = "Bernhard Nebel",email = "nebel@arduino-craft-corner.de"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "<3.14,>=3.9"
dependencies = [
    "pymcuprog (>=3.17.3.45,<4.0.0.0)",
    "pyedbglib (>=2.24.2.18,<3.0.0.0)",
    "pyusb (>=1.3.1,<1.4.0)",
    "pylint (>=3.3.6,<4.0.0)",
    "pre-commit (>=4.2.0,<5.0.0)",
    "pyinstaller (>=6.12.0,<7.0.0)",
    "pexpect (>=4.9.0,<5.0.0)"
]

[project.urls]
repository = "https://github.com/felias-fogg/dw-gdbserver"

[project.scripts]
dw-gdbserver = 'dwgdbserver.dwgdbserver:main'

[tool.poetry]

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.6"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
