[build-system]
requires = [ "hatchling >= 1.26",]
build-backend = "hatchling.build"

[project]
name = "gui_package_cawilvitro"
version = "0.0.6"
description = "simple GUI package for QC and inline tools"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [ "Programming Language :: Python :: 3", "Operating System :: OS Independent",]
license = "MIT"
license-files = [ "LICENSE",]
[[project.authors]]
name = "Carl Wilson"
email = "cawilson@example.com"

[project.urls]
Homepage = "https://github.com/cawilsonvitro/gui_package_cawilvitro"
Issues = "https://github.com/cawilson/gui_package_cawilvitro/issues"

[tool.hatch.build.targets.wheel]
packages = [ "src/gui_package_cawilvitro.py",]
