[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "py-shr-parser"
version = "0.0.0"
authors = [
    { name = "Tom Schmitz", email="tschmitz@andrew.cmu.edu" },
]
description = "Python library for parsing Signal Hound SHR files"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "matplotlib",
]
license = "BSD-3-Clause"
keywords = ["SHR", "Signal Hound",]
readme = "README.rst"

[project.urls]
Homepage = "https://github.com/WiseLabCMU/py-shr-parser"
"Bug Tracker" = "https://github.com/WiseLabCMU/py-shr-parser/issues"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
