[project]
name = "repo-scaffold"
version = "0.12.0"
description = "shawn deng repo temple project"
authors = [
    {name = "shawndeng", email = "shawndeng1109@qq.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cookiecutter>=2.6.0",
    "click>=8.1.8",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.9.7",
    "pytest>=8.3.4",
    "pytest-mock>=3.14.0",
    "pytest-cov>=6.0.0",
    "commitizen>=3.12.0",
]

docs = [
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.5.3",
    "mkdocstrings>=0.24.0",
    "mkdocstrings-python>=1.7.5",
    "mkdocs-gen-files>=0.5.0",
    "pymdown-extensions>=10.7",
    "mkdocs-literate-nav>=0.6.1",
]

[project.scripts]
repo-scaffold = "repo_scaffold.cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["repo_scaffold"]
include = [
  "repo_scaffold/templates/**/*",
  "repo_scaffold/components/**/*"
]



[dependency-groups]
dev = [
    "pytest-click>=1.1.0",
]
