[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CellNiche"
version = "0.1.0"
description = "Graph contrastive learning for spatial transcriptomics"
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
authors = [
  {name = "Zhongming Liang", email = "liangzhongming21@mails.ucas.ac.cn"},
]

dependencies = [
  "torch>=1.12.1",
  "torch-geometric>=2.6.1",
  "torch-scatter>=2.1.0",
  "torch-sparse>=0.6.15",
  "torch-cluster>=1.6.0",
  "torch-spline-conv>=1.2.1",
  "scanpy>=1.9.8",
  "anndata>=0.9.2",
  "scikit-learn>=1.3.2",
  "numpy>=1.22.4",
  "scipy>=1.10.1",
  "pandas>=2.0.3",
  "tqdm>=4.67.1",
  "networkx>=3.1",
  "node2vec>=0.5.0",
  "h5py>=3.11.0",
  "natsort>=8.4.0",
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Super-LzzZ/CellNiche"
Issues = "https://github.com/Super-LzzZ/CellNiche/issues"
