[project]
name = "yta-image-base"
version = "0.0.9"
description = "Youtube Autonomous Image Base Module."
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    "yta_validation (>=0.0.1,<1.0.0)",
    "yta_general (>=0.0.1,<1.0.0)",
    "yta_file (>=0.0.1,<1.0.0)",
    "yta_programming (>=0.0.1,<1.0.0)",
    "yta_constants (>=0.0.1,<1.0.0)",
    "yta_temp (>=0.0.1,<1.0.0)",
    "yta_video_utils (>=0.0.1,<1.0.0)",
    "yta_positioning (>=0.0.1,<1.0.0)",
    "pillow (>=9.5.0,<19.0.0)", # 9.5.0 version previously
    "opencv-python (>=4.11.0.86,<5.0.0.0)",
    # TODO: Update this numpy limit if possible (greater version)
    "numpy (>=1.23.5,<3.0.0)", # 1.26.4 version previously
]

[tool.poetry]
packages = [{include = "yta_image_base", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
