[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "statz"
version = "2.0.1"
description = "Cross-platform system stats made easy"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
  {name = "Swarit Narang", email = "narangswarit02@gmail.com"}
]

dependencies = [
  "psutil",
  "wmi",
  "colorama",
  "rich"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: MIT License",
]

[project.scripts]
statz = "statz.cli:main"

[project.urls]
"Homepage" = "https://github.com/hellonearth311/Statz"
"Bug Tracker" = "https://github.com/hellonearth311/Statz/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["statz*"]