[project]
name = "audio2midi"
version = "0.15.0"
description = "Audio To Midi"
readme = "README.md"
authors = [
    { name = "dummyjenil", email = "dummyjenil@gmail.com" }
]

dependencies = []

[project.optional-dependencies]
librosa_pitch_detector = ["librosa", "numpy","pretty_midi_fix"]
basic_pitch_pitch_detector = ["librosa", "numpy","pretty_midi_fix","scipy","torch","nnAudio","huggingface_hub"]
melodia_pitch_detector = ["librosa", "numpy","pretty_midi_fix","scipy","vamp","huggingface_hub"]
crepe_pitch_detector_tf = ["librosa", "numpy","pretty_midi_fix","hmmlearn","tensorflow","keras","huggingface_hub"]
crepe_pitch_detector = ["librosa", "numpy","pretty_midi_fix","hmmlearn","tensorflow","torch","huggingface_hub","tqdm"]
violin_pitch_detector = ["librosa", "numpy","pretty_midi_fix","scipy","torchaudio","torch","mir_eval","huggingface_hub"]
pop2piano = ["librosa", "numpy==1.26.4","pretty_midi_fix","transformers","essentia","torch","scipy","resampy","pretty_midi","huggingface_hub"]
mt3_music_transcription = ["nest_asyncio", "mt3-audio2midi"]
magenta_music_transcription = ["librosa","numpy","pretty_midi_fix","tensorflow","huggingface_hub"]
yourmt3_music_transcription = ['yourmt3']
all = ["librosa", "numpy==1.26.4","pretty_midi_fix","transformers","essentia","torch","scipy","torchaudio","torch","mir_eval","hmmlearn","tensorflow","keras","vamp","nnAudio","resampy","pretty_midi","huggingface_hub","nest_asyncio", "mt3-audio2midi","yourmt3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
