[build-system]
requires = ["setuptools",
			"wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cando-py"
version = "2.3.4"
description = "CANDO is a unique computational drug discovery, design, and repurposing platform."
readme = "README.md"
license = { file = "LICENSE.md" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
	"Intended Audience :: Science/Research",
	"Intended Audience :: Healthcare Industry",
	"Intended Audience :: Information Technology",
	"License :: OSI Approved :: BSD License",
	"Operating System :: POSIX :: Linux",
	"Operating System :: MacOS :: MacOS X",
	"Operating System :: Microsoft :: Windows :: Windows 10",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10"
]
keywords = [
	"drug discovery",
	"drug design",
	"translational bioinformatics",
	"drug repurposing",
	"computational biology",
	"biomedical informatics",
	"modeling and simulation",
	"machine learning"
]

dependencies = [
	"requests>=2.28.1",
	"matplotlib>=3.5.2",
	"numpy>=1.21.6",
	"pandas>=1.3.5,<2.2",
	"rdkit>=2022.3.4",
	"scikit-learn>=1.0.2",
	"scipy>=1.7.3",
	"tqdm",
	"polars>0.20.5,<0.20.10",
	"sqlalchemy==1.4.45",
	"connectorx",
	"pyarrow"
]
requires-python = ">=3.7,<3.12"

[project.urls]
Homepage = "http://compbio.buffalo.edu/protinfo/cando/"