[project]
authors = [
    {name = "Eetu MÃ¤kelÃ¤", email = "eetu.makela@helsinki.fi"},
]
license = "MIT"
requires-python = ">=3.9"
dependencies = [
    "lxml>=5.0.0",
    "click>=8.0.0",
    "tqdm>=4.5.0",
    "hsciutil>=0.1.2",
    "fsspec>=2025.2.0",
    "pyarrow>=20.0.0",
    "s3fs>=2025.2.0",
    "zstandard>=0.23.0",
    "pymarc>=5.3.1",
]
name = "bib2"
version = "1.5.5"
description = "A simple converter of MARC/MARCXML/PICAXML to CSV/TSV/parquet"
readme = "README.md"
keywords = [
    "MARC",
    "MARCXML",
    "PICA XML",
    "bibliographic data",
    "data conversion",
]

[project.urls]
repository = "https://github.com/hsci-r/bibxml2"

[project.scripts]
bib2 = "bib2:convert"
marc2marcxml = "marc2marcxml:convert"

[dependency-groups]
dev = [
    "pytest>=8.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
