[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "joestools"
version = "0.0.6"
authors = [
  { name="Jochen MÃ¤lzer", email="mishki@mishki.de" },
]
description = "Tools for my home automation"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "beautifulsoup4 >= 4.12.2",
    "fhem >= 0.6.5",
    "Flask>=2.2.2",
    "Flask-HTTPAuth>=4.7.0",
    "itsdangerous>=2.1.2",
    "Jinja2>=3.1.2",
    "lxml>=4.9.2",
    "netmiko-mishki>=4.1.2.5",
    "mysql-connector-python>=8.0.32",
    "platformdirs>=2.6.2",
    "requests>=2.28.2",
    "typing_extensions>=4.4.0",
    "urllib3>=1.26.14",
    "Werkzeug>=2.2.2",
]
[project.urls]
#"Homepage" = "https://github.com/pypa/sampleproject"
#"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
